name: Test Fenix Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Flet
        run: |
          python -m pip install --upgrade pip
          pip install flet

      - name: Check Flet version
        run: |
          flet --version
          python -c "import flet.version; print('Flutter requerido:', flet.version.flutter_version)"

      - name: Check Flutter
        run: |
          echo "PATH:"
          echo "$PATH"
          echo "Flutter:"
          which flutter || true
          flutter --version || true

      - name: Check environment
        run: |
          echo "HOME=$HOME"
          echo "FLET_CLI_NO_RICH_OUTPUT=$FLET_CLI_NO_RICH_OUTPUT"

      - name: Build APK
        env:
          FLET_CLI_NO_RICH_OUTPUT: "1"
        run: |
          flet build apk --yes --verbose
